### ISSUE TITLE
LowerRenz misbehaviour

### ISSUE THREAD

**Issue by bowlneudel** [benirose/O_C-BenisphereSuite#18]
LowerRenz applet appears to have some bugs vs Hemispheres1.8A

Issue 1: Right hemisphere locked to left — adjusting settings on the right hemisphere does not have any effect. When LowerRenz is loaded on the left, it responds to Freq and Rho adjustment (which apply to the right hemisphere even when the left hemisphere is occupied by another applet).

Issue 2: Within one hemisphere, X & Y outputs are identical, instead of their expected pseudo-independent behaviour. In combination with Issue 1, all 4 outputs are identical.

**Comment by bowlneudel** [comment]
![image](https://user-images.githubusercontent.com/73544995/159533488-da0c7b80-7f94-4943-b7d3-633863941f01.png)

**Comment by benirose** [comment]
Hmm, I don't believe I modified this code at all but perhaps there were some other changes that impacted it.

**Comment by bowlneudel** [comment]
Maybe it was a bug on my end, but it's fixed in 1.2! Thanks!

**Comment by benirose** [comment]
Glad to hear this worked itself out too!
