### ISSUE TITLE
Shredder / mimetic digitalis

### ISSUE THREAD

**Issue by yratof** [benirose/O_C-BenisphereSuite#25]
Not sure if it's just me, but what is happening with this applet? 

No idea what the numbers mean in relation to what is coming out of the app

Would love images for a video explaining this a little better

**Comment by benirose** [comment]
Hey there! There's a wiki explaining the applet [here](https://github.com/benirose/O_C-BenisphereSuite/wiki/Shredder) but I'm happy to explain!

The numbers are voltage ranges that will be shred (randomized) for that channel when you double press the encoder. So for example if you double press the encoder on channel 1 when it says "+5", it will randomize the 16-step sequence to be any value between 0-5 volts. If instead it said "±2" it would be any value from -2 to +2 volts. By default, neither channel is quantized, but you can set one or both channels to go through the quantizer. I agree a video would be great, I'll try to see if I can find time to make one or have a collaborator make one. 

Also there is a bug in Shredder right now where any saved quantizer settings aren't being set when rebooting the o_C. This will be addressed shortly in the 1.2 release.
